ginMode: release
port: 9000
token:
  timeout: 7200

job:
  mysql: root:Huijia@2020@tcp(172.21.0.2:3306)/jiwadou?charset=utf8mb4&loc=Local

mp:
  appid: wxacfa20737ca2eb1a
  appsecret: 0f4bd4fc0e88deffe58f1c294475842f

logPath: /opt/jiwadou/log/